#server:
#  port: 8001
#spring:
#  application:
#    name: cloud-provider-hystrix-payment
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: payment8001  #更改实例名称
    #eureka客户端向服务端发送心跳的时间间隔
    lease-renewal-interval-in-seconds: 1
    #eureka服务端接收最后一次心跳的时间间隔
    lease-expiration-duration-in-seconds: 2
#      defaultZone: http://localhost:7001/eureka

server:
  port: 8001
spring:
  application:
    name: cloud-provider-payment
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.200:3306/jdbc?useUnicode=true&amp&useSSL=false&amp&characterEncoding=UTF-8&amp&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entity #所有entity别名类包

