server:
  port: 80

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
#      defaultZone: http://localhost:7001/eureka

spring:
  application:
    name: cloud-order-service
